#ifndef FIELD_H
#define FIELD_H
#include <fstream>
#include <iostream>
#include <json11.hpp>
#include "level/mapnode.h"
#include "misc/util.h"

class Field {
private:
  std::vector<std::vector<NodeBase>> mapBase; //!< The level data of the map
  sf::Vector2i tilesize;
public:
  //! returns a copy of specified node
  NodeBase getNode(unsigned, unsigned) const;
  //! overwrites the mapnode at position x,y with node
  void updateNode(unsigned x, unsigned y, const NodeBase& node);
  //! Gets map height
  int getHeight() const;
  //! Gets map width
  int getWidth() const;

  //! gets tile width
  int getTilesizeX() const;
  //! gets tile height
  int getTilesizeY() const;
  //! gets tilesize as a sf::Vector2i
  sf::Vector2i getTilesize() const;

  //! Constructs a field with specified size
  Field(size_t, size_t);

  //! Loads mapBase from file, specified by argument.
  /*! 
   *  Searches for file in /levels/
   */
  int loadLevel(const std::string&);
  //! Loads tiles from a json file generated by OGMO editor
  int loadJsonLevel(const std::string& levelname);
  //! Determines how far object with specified size, pos, speed, can move without hitting something
  sf::Vector2f validMove(sf::Vector2f pos, sf::Vector2f size, sf::Vector2f speed) const;

  //! A wrapper for validMove
  //sf::Vector2f wallPush(const Object* o, sf::Vector2f move) {
};

//! parses a string containing a node, uses nodify
bool nodify(std::string&, MapNode&);
//! creates a node from a string representation of a node
bool strToNode(const std::string&, MapNode&);

#endif
